### ISSUE TITLE
Unable to install 

### ISSUE THREAD

**Issue by kylerove** [OWS/commonmark-sup-sub-extensions#1]
I have common mark 0.17 installed, php 7.1 with mbstring and I get this error:
[InvalidArgumentException]                                                                                                   
  Could not find a version of package ows/commonmark-sup-sub-extensions matching your minimum-stability (stable). Require it   
  with an explicit version constraint allowing its desired stability.

Haven't had time to investigate, but by removing mbstring requirement and removing |1.0 reference (can't see how that would be cause) from composer.json, it installs fine.

**Comment by Sylry** [comment]
There was not yet a stable version: 1.0.0-RC1: https://packagist.org/packages/ows/commonmark-sup-sub-extensions

I just published 1.0.0 version and now, in an empty directory, I can run `composer require ows/commonmark-sup-sub-extensions`:

```
$ composer require ows/commonmark-sup-sub-extensions
Using version ^1.0 for ows/commonmark-sup-sub-extensions
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 2 installs, 0 updates, 0 removals
  - Installing league/commonmark (0.17.5): Downloading (100%)         
  - Installing ows/commonmark-sup-sub-extensions (1.0.0): Downloading (100%)         
league/commonmark suggests installing league/commonmark-extras (Library of useful extensions including smart punctuation)
Writing lock file
Generating autoload files
```
