### ISSUE TITLE
Add changelog

### ISSUE THREAD

**Issue by pazairfog** [OWS/commonmark-sup-sub-extensions#15]
Examples : 
* https://github.com/drush-ops/drush/blob/master/README.md
* https://keepachangelog.com/en/1.1.0

**Comment by Sylry** [comment]
As discussed with @defr, it might ba a false good idea because:
* it is not actually code
* it will cause merge conflicts if each commit should add a line in "## [Unreleased]" part

**Comment by pazairfog** [comment]
I finally found reason.
