### ISSUE TITLE
Add compatibility with league/commonmark 1.0

### ISSUE THREAD

**Issue by Sylry** [OWS/commonmark-sup-sub-extensions#6]
In a 2.0 branch

**Comment by defr** [comment]
Played a bit with the 2.x branch, and I think there's still a few issue, we're still not playing nice the various other inline processors that could run.

We probably should rewrite the two extensions, removing the parser and instead making use of the new DelimiterProcessorInterface introduced in 1.0, and get our code a lot closer EmphasisDelimiterProcessor. I think doing so would fix #4 as a free bonus.
