### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by Sylry** [OWS/commonmark-sup-sub-extensions#7]

**Comment by Sylry** [comment]
Basic tests added and phpstan tool

Some more tests are welcome :-)

**Comment by defr** [comment]
I've got a bunch of tests to add, but I'd rather wait for both #8 ( to make it easier to add thoses tests without rewriting everything all the time) and #9 ( to avoid introducing incorrect assumptions in test that'll need to be updated once the parser works correctly :wink:  ) before doing so.
